version: '3.8'

services:
  dataeng-cassandra:
    image: docker.io/bitnami/cassandra:latest
    container_name: ${CASSANDRA_CONTAINER_NAME}
    hostname: ${CASSANDRA_HOST}
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
networks:
  default:
    name: dataeng-network
    external: true