version: '2'

services:
  dataeng-spark-master:
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    hostname: ${SPARK_MASTER_HOST_NAME}
    image: dataeng/spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../spark-scripts:/spark-scripts
      - ../scripts:/scripts
    ports:
      - ${SPARK_MASTER_UI}:8080
      - ${SPARK_MASTER_PORT}:7077

  dataeng-spark-worker-1:
    &worker_default
    container_name: ${SPARK_WORKER_CONTAINER_NAME}-1
    image: dataeng/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://${SPARK_MASTER_HOST_NAME}:${SPARK_MASTER_PORT}
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_JARS_PACKAGES=com.datastax.spark:spark-cassandra-connector_2.12:3.3.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0

    volumes:
      - ../spark-scripts:/spark-scripts
      - ../scripts:/scripts
    depends_on:
      - dataeng-spark-master

  # dataeng-spark-worker-2:
  #   <<: *worker_default
  #   container_name: ${SPARK_WORKER_CONTAINER_NAME}-2

networks:
  default:
    name: dataeng-network
    external: true
